@startuml
set separator none
title Software System - System Context

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

Person(eMPLOYEES, "eMPLOYEES", $descr="", $tags="", $link="")
System(SoftwareSystem, "Software System", $descr="", $tags="", $link="")

Rel(eMPLOYEES, SoftwareSystem, "hola", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml